# Generated by Django 6.0.5 on 2026-05-21 14:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = [
    migrations.swappable_dependency(settings.AUTH_USER_MODEL),
  ]

  operations = [
    migrations.CreateModel(
      name='Patient',
      fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('first_name', models.CharField(max_length=128)),
        ('last_name', models.CharField(max_length=128)),
        ('date_of_birth', models.DateField()),
        ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=16)),
        ('phone_number', models.CharField(max_length=8, unique=True, validators=[
          django.core.validators.RegexValidator(message='Phone number must be 8 digits starting with 8 or 9',
                                                regex='^[89]\\d{7}$')])),
        ('address', models.CharField(max_length=128)),
        ('medical_history', models.TextField()),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('user',
         models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
      ],
      options={
        'db_table': 'patient',
      },
    ),
  ]
